---
title: "Tareas"
author: "Aleksander Dietrichson"
lang: es-AR
format: html
editor: visual
---

Las tareas se realizan luego de cada clase y se entregan por medio de un pull request (PR) al repositorio.

## Tarea 1

1.  Generar un conjunto de datos aleatoreos (usar "sample")
2.  Asignarlo a una variable (p.e. x)
3.  Repetir el proceso (usar el mismo largo, y p.e. y)
4.  Generar de los dos vectores un data.frame
5.  Visualizarlo

Pregunta: Hay algun patrón?

## Tarea 2

1.  Armar un Google Sheet con textos periodisticos (10)
2.  Acceder al mismo desde R
3.  Realizar analisis como el de este documento. (Numero de palabras, y promedio de largo de palabras).

### Medios asignados a los participantes:

-   Nico - Clarin

-   Thiago - La Nacion

-   Camila - Ambito

-   Ornella - Infobae

-   Belen - Tiempo Argentino

## Tarea 3

1.  Ampliar analysis ya hecho con visualizacion en ggplot2
2.  Aplicar uso de stopwords y generar analysis de frecuencias de la palabras del medio eligido.

## Tarea 4

1.  Haciendo uso del medio al que fue asignado eligir una palabra clave buscar su frecuencia en el medio eligido.
2.  Eligir otro medio de los disponibles, calcular su frecuencia.
3.  Formular una hipótesis sobre la frecuencia comparativa.
4.  Testear la hipótesis e interpretar los resultados.

## Tarea 5

1.   Sacar dos muestras de algún periódico de los que hemos scrapeado.

2.  Formular hipótesis sobre p.e. largo de las notas

3.  Testear la hipótesis con test de T.
